# Generated by Django 5.1 on 2024-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='A Collaborative Person', max_length=150, null=True),
        ),
    ]
